In [3]:
import numpy as np 
import matplotlib.pyplot as plt

Printing digits with for loops. 
The range() function returns a sequence of numbers, starting from 0 and increments by 1 but does *not include the last number*

In [ ]:
for i in range (1,11): 
	print(i)

### Nested For Loop

In [ ]:
num_list = [1,2,3]
alpha_list = ['a', 'b', 'c']

for number in num_list: 
	print(number)
	for letter in alpha_list: 
		print(letter)

### Generating Matrix with nested for loop

Here we are creating a matrix of zeros, 3 rows, 6 columns. We will have i represent rows and j represent columns. 

Once we are in the inner loop, during the first iteration, we will be at the first row, first column and fill each entry with 8. We will then move over to each column and repeat the process until the whole matrix is filled. 

In [4]:
x = np.zeros((3,6))
for i in range(0,3): 
	for j in range(0,6): 
		x[i][j] = 8
print(x)

[[8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8.]]
