# Dealing with arrays

In [ ]:
import numpy as np

# 1-D Array
a = np.array([0,1,2,3,4,5,6,7,8,9])

print(a)

# 2-D Array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

### Check the size or dimension of the array


In [ ]:
# Find the dimension of an array
print(b.shape)

# Find the size of an array
print(a.size)

### arange

In [ ]:
import numpy as np

c = np.array([0,1,2,3,4,5,6,7,8,9])

# a faster method to creating an array is to use arange

d = np.arange(0,10) # NOTE: we do not include the last element e.g. 0-9
print(d)

In [ ]:
# We can also add intervals for arange

a = np.arange(0,101,2)

print(a)

### linspace

In [ ]:
# Useful for generating sample points for plotting or analysis 

x1 = np.linspace(0,20,5) # start, finish, number of elements we need
x1 # result will print 5 elements

array([ 0.,  5., 10., 15., 20.])

### reshape

In [14]:
y = np.arange(0,25)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [16]:
# verify shape
print(y.shape)

# now we will convert a 1-D array into a 5x5 2-D array

y = y.reshape(5,5)
print(y)

(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
